name: Deploy Express.js App to VPS

on:
  push:
    branches:
      - main # Replace with your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.PRIVATE_SSH_KEY }}

      - name: Deploy to VPS
        env:
          VPS_HOST: ${{ secrets.HOST }}
          VPS_USER: ${{ secrets.USERNAME }}
        run: |
          ssh $VPS_USER@$VPS_HOST << 'EOF'
            # Change to your app directory
            cd 

            # Pull latest changes
            sudo git pull origin main

            # Install dependencies
            sudo npm install

            # Restart the app (using PM2 for example)
            pm2 restart all || pm2 start app.js --name my-express-app
          EOF
